# Generated by Django 4.0.1 on 2022-01-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='images',
            new_name='imagens',
        ),
    ]
